force-app/main/default/objects/Product_Inventory__c/Product_Inventory__c.object-meta.xml
<CustomObject>
    <label>Product Inventory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Inventory__c/fields/Amount_Available__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available__c</fullName>
    <label>Amount Available</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Inventory_Month__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Month__c</fullName>
    <label>Inventory Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Inventory_Year__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Year__c</fullName>
    <label>Inventory Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Item__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouses for LeafMeAlone</description>
    <label>Warehouse</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductInventoryBatch.cls
public class ProductInventoryBatch implements Database.Batchable<sObject> {
    
    //start
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(
            [SELECT Id, Name, Product__c, Warehouse__c, Inventory_Month__c, Inventory_Year__c, Amount_Available__c, Current__c
             FROM Product_Inventory__c 
             WHERE Current__c = TRUE]
        );
    }
    
    //execute
    public void execute(Database.BatchableContext BC, List<Product_Inventory__c> scope){
        List <Product_Inventory__c> updateProdInvList = new List<Product_Inventory__c>();
        List <Product_Inventory__c> newProdInvList = new List<Product_Inventory__c>();
        
        for(Product_Inventory__c oldRec : (List<Product_Inventory__c>) scope){
            //container for new records
            Product_Inventory__c newRec = new Product_Inventory__c();
            
            //Regex to get the [0] name, [1] month, and [2] year
            String[] regexName = oldRec.Name.split('(?<=\\D)(?=\\d)');
            newRec.Name = regexName[0];
            newRec.Inventory_Month__c = Date.today().month();
            newRec.Inventory_Year__c = Date.today().year();
            newRec.Amount_Available__c = oldRec.Amount_Available__c;
            newRec.Product__c = oldRec.Product__c;
            newRec.Warehouse__c = oldRec.Warehouse__c;
            newRec.Current__c = true;
            //change old recs to false
            oldRec.Current__c = false;
            
            //add to list to bulkify
            newProdInvList.add(newRec);
            updateProdInvList.add(oldRec);
        }
        
        if(newProdInvList.size() > 0){
            Insert newProdInvList;
            Update updateProdInvList;
        }
    }
    
    //finish
    public void finish(Database.BatchableContext BC){
        
    }
}