force-app/main/default/objects/Product_Inventory__c/Product_Inventory__c.object-meta.xml
<CustomObject>
    <label>Product Inventory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Inventory__c/fields/Amount_Available__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available__c</fullName>
    <label>Amount Available</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Item__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Item__c/Product_Item__c.object-meta.xml
<CustomObject>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouses for LeafMeAlone</description>
    <label>Warehouse</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductItemController.cls
public class ProductItemController {
    
    @AuraEnabled
    public static List<Product_Inventory__c> getWarehouseByProdName(String searchKey){
        searchKey = '%' + searchKey + '%';
        return [SELECT Id, Amount_Available__c, Product__r.Name, Product__r.Product_Code__c, Warehouse__r.Name, Current__c
                FROM Product_Inventory__c 
                WHERE Product__r.Name != :searchKey 
                OR Product__r.Product_Code__c != :searchKey];
    }
    
    @AuraEnabled
    public static List<Warehouse__c> getAllWarehouse(){
        return [SELECT Id, Name FROM Warehouse__c];
    }
    
    @AuraEnabled
    public static void saveProdItem(String prodName, String prodCode){
        Product_Item__c prod = new Product_Item__c();
        prod.Name = prodName;
        prod.Product_Code__c = prodCode;
        insert prod;
        
        //insert to product inventory
    }

}