force-app/main/default/objects/Incoming_Shipment__c/Incoming_Shipment__c.object-meta.xml
<CustomObject>
    <label>Incoming Shipment</label>
    <nameField>
        <displayFormat>IS{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incoming Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Incoming_Shipment__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incoming_Shipment__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Incoming Shipments</relationshipLabel>
    <relationshipName>Incoming_Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouses for LeafMeAlone</description>
    <label>Warehouse</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse__c/fields/Warehouse_Code__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Code__c</fullName>
    <externalId>true</externalId>
    <label>Warehouse Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/WSIncomingShipment.cls
@RestResource(urlMapping='/WSIncomingShipment')
global class WSIncomingShipment {
	
    @HttpPost
    global static void insertIncomingShipment(){
        //create vars to hold data from arc
        String prodCode, warehouse, response;
        Integer count;
        
        //retrieve JSON body
        String body = RestContext.request.requestBody.toString();
        
        NewIncShipment ship = (NewIncShipment) JSON.deserialize(body, NewIncShipment.class);
        prodCode = ship.ProductCode;
        count = ship.count;
        warehouse = ship.warehouse;
        system.debug(ship);
        
        //Query warehouse id
        Warehouse__c getWarehouseId = [SELECT Id, Warehouse_Code__c, Name
                                       From Warehouse__c
                                       WHERE Warehouse_Code__c = :warehouse];
        
        //Check if fields are null
        if(prodCode != null && count != null && warehouse != null){
            //Insert new incoming shipment method
            Incoming_Shipment__c newRec = new Incoming_Shipment__c();
            newRec.Product_Code__c = prodCode;
            newRec.Count__c = count;
            newRec.Warehouse__c = getWarehouseId.Id;
            
            insert newRec;
            response = 'Inserted with Id: ' + newRec.Id;
        }
        else{
            response = 'Values should not be null';
        }
        Restcontext.response.responseBody = blob.valueof(response);
    }
    
    //Wrapper to receive JSON data 
    public class NewIncShipment{
        public String ProductCode;
        public Integer count;
        public String warehouse;
    }
    
}