force-app/main/default/objects/Incoming_Shipment__c/Incoming_Shipment__c.object-meta.xml
<CustomObject>
    <label>Incoming Shipment</label>
    <nameField>
        <displayFormat>IS{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incoming Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Incoming_Shipment__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Incoming_Shipment__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Incoming Shipments</relationshipLabel>
    <relationshipName>Incoming_Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/Product_Inventory__c.object-meta.xml
<CustomObject>
    <label>Product Inventory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Inventory__c/fields/Amount_Available__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available__c</fullName>
    <label>Amount Available</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Item__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Item__c/Product_Item__c.object-meta.xml
<CustomObject>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Item__c/fields/Total_Available_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Available_Count__c</fullName>
    <description>Get the latest product inventories from all warehouses</description>
    <label>Total Available Count</label>
    <summarizedField>Product_Inventory__c.Amount_Available__c</summarizedField>
    <summaryForeignKey>Product_Inventory__c.Product__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouses for LeafMeAlone</description>
    <label>Warehouse</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IncomingShipmentTriggerHandler.cls
public class IncomingShipmentTriggerHandler {
    
    public static void incomingShipmentInsert(List<Incoming_Shipment__c> shipList) {
        Set<String> prodCodeSet = new Set<String>();
        Set<String> warehouseSet = new Set<String>();
        
        for(Incoming_Shipment__c ship : shipList){
            //add values to containers
            prodCodeSet.add(ship.Product_Code__c);
            warehouseSet.add(ship.Warehouse__c);
        }
		
        //Check product from Product_Item_c
        List<Product_Item__c> prodItemList = [SELECT Id, Product_Code__c, Total_Available_Count__c
                                              FROM Product_Item__c
                                              WHERE Product_Code__c IN: prodCodeSet];
        
        List<Product_Inventory__c> prodInvList = [SELECT Id, Warehouse__c, Amount_available__c, Product__r.Product_code__c
                                                  FROM Product_inventory__c
                                                  WHERE Warehouse__c IN: warehouseSet
                                                  AND Current__c = TRUE
                                                  AND Product__r.Product_code__c IN: prodCodeSet];

        for(Incoming_Shipment__c ship : shipList){
            if(prodItemList.size() == 0){
                //no match found
                ship.addError('No product found');
            }
            else if(prodItemList.size() != 0){
                Boolean flag = false;
                //compare products with same warehouse between product inventory and incoming shipment
                for(Product_Inventory__c inv : prodInvList){
                    if(ship.Product_Code__c == inv.Product__r.Product_code__c){
                        //increment amount available in inventory
                        inv.Amount_available__c = inv.Amount_available__c + ship.Count__c;
                        flag = true;
                    }
                }
                //create product inventory bool if flag is false
            }
        }
        //update inventory
        if(prodInvList != null && prodInvList.size() > 0)
        	update prodInvList;
    }
}