force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/From_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>From_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Route__c.field-meta.xml
<CustomField>
    <fullName>Route__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route</label>
    <referenceTo>Route__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parked</fullName>
                <default>true</default>
                <label>Parked</label>
            </value>
            <value>
                <fullName>En-route</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/To_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>To_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Deliveries (To Warehouse)</relationshipLabel>
    <relationshipName>Deliveries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <referenceTo>Truck__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Content__c/Delivery_Content__c.object-meta.xml
<CustomObject>
    <label>Delivery Content</label>
    <nameField>
        <displayFormat>DC{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Contents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Content__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Delivery Contents</relationshipLabel>
    <relationshipName>Delivery_Contents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Delivery_Content__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Product_Item__c</referenceTo>
    <relationshipLabel>Delivery Contents</relationshipLabel>
    <relationshipName>Delivery_Contents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/Product_Inventory__c.object-meta.xml
<CustomObject>
    <label>Product Inventory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Inventory__c/fields/Amount_Available__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available__c</fullName>
    <label>Amount Available</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Item__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Product Inventories</relationshipLabel>
    <relationshipName>Product_Inventories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Item__c/Product_Item__c.object-meta.xml
<CustomObject>
    <label>Product Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/Route__c.object-meta.xml
<CustomObject>
    <label>Route</label>
    <nameField>
        <label>Route Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route__c/fields/From_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>From_Warehouse__c</fullName>
    <label>From Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Routes</relationshipLabel>
    <relationshipName>Routes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/To_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>To_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>To Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Routes (To Warehouse)</relationshipLabel>
    <relationshipName>Routes1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route__c/fields/Travel_Time_mins__c.field-meta.xml
<CustomField>
    <fullName>Travel_Time_mins__c</fullName>
    <label>Travel Time (mins)</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Truck__c/Truck__c.object-meta.xml
<CustomObject>
    <label>Truck</label>
    <nameField>
        <label>Plate #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parked</fullName>
                <default>true</default>
                <label>Parked</label>
            </value>
            <value>
                <fullName>On Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <description>Warehouses for LeafMeAlone</description>
    <label>Warehouse</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NewDeliveryController.cls
public with sharing class NewDeliveryController {


    @AuraEnabled(Cacheable=true)
    public static List<Warehouse__c> getWarehouse(){
        return [Select Id, Name
                FROM Warehouse__c];
    }

    @AuraEnabled(cacheable=true)
    public static String getETA(Id fromWarehouseValue, Id toWarehouseValue){
        Route__c eta = [SELECT Id, Name, From_Warehouse__r.Name, To_Warehouse__r.Name, Travel_Time_mins__c 
                        FROM Route__c
                        WHERE From_Warehouse__c = :fromWarehouseValue
                        AND To_Warehouse__c = :toWarehouseValue];

        DateTime now = Datetime.now();
        DateTime adjusted = now.addMinutes((Integer)eta.Travel_time_mins__c);
        String formatTime = adjusted.format('h:mm a');

        return formatTime;
    }

    //get trucks
    @AuraEnabled(Cacheable=true)
    public static List<Truck__c> getTrucks(Id fromWarehouseValue){
        return [Select Id, Name, Status__c 
                FROM Truck__c
                WHERE Status__c = 'Parked'];
    }

    //get data for table
    @AuraEnabled(Cacheable=true)
    public static List<DataWrapper> getDeliveryContents(Id fromWarehouseValue){
        List<DataWrapper> dataWrapperList = new List<DataWrapper>();
        List<Product_Inventory__c> prodList = [Select Id, Product__r.Name, Name, Warehouse__r.Name, Amount_Available__c, Product__c
                                               FROM Product_Inventory__c 
                                               WHERE Current__c = true
                                               AND Warehouse__c = :fromWarehouseValue];

        for(Product_Inventory__c prod : prodList){
            dataWrapperList.add(new DataWrapper(prod));
        }
        return dataWrapperList;
    }

    //save new delivery
    @AuraEnabled
    public static void insertNewDelivery(Id fromWarehouse, Id toWarehouse, Id truck, String status, String deliveryContentsList){
        //for bulkify
        List<Delivery_Content__c> insertDelContentList = new List<Delivery_Content__c>();

        //deserialize wrapper
        List<DataWrapper> deliveryList = (List<DataWrapper>) JSON.deserialize(deliveryContentsList, List<DataWrapper>.class);

        //query routeId
        Route__c route = [Select Id, Name 
                          FROM Route__c WHERE From_Warehouse__c = :fromWarehouse 
                          AND To_Warehouse__c = :toWarehouse];

        //insert delivery
        Delivery__c newDel = new Delivery__c();
        newDel.Name = 'Temp';
        newDel.Truck__c = truck;
        newDel.From_Warehouse__c = fromWarehouse;
        newDel.To_Warehouse__c = toWarehouse;
        newDel.Route__c = route.Id;
        newDel.Status__c = status;
        insert newDel;

        //insert delivery content
        for(DataWrapper d  : deliveryList){
            Delivery_Content__c newRec = new Delivery_Content__c();
            newRec.Item__c = d.prodItemId;
            newRec.Delivery__c = newDel.Id;
            newRec.Amount__c = d.deliveryAmount; 

            insertDelContentList.add(newRec);
        }

        if(insertDelContentList != null && insertDelContentList.size() > 0){
            insert insertDelContentList;
        }
    }

    public class DataWrapper{        
        @AuraEnabled public Id prodItemId;
        @AuraEnabled public String prodName;
        @AuraEnabled public Decimal amountAvailable;
        @AuraEnabled public Decimal deliveryAmount;
        
        public DataWrapper(Product_Inventory__c rec){
            this.prodItemId = rec.Product__c;
            this.prodName = rec.Product__r.Name;
            this.amountAvailable = rec.Amount_Available__c;
            this.deliveryAmount = 0;
        }
    }
}