force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <label>Delivery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parked</fullName>
                <default>true</default>
                <label>Parked</label>
            </value>
            <value>
                <fullName>En-route</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/To_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>To_Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Deliveries (To Warehouse)</relationshipLabel>
    <relationshipName>Deliveries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <referenceTo>Truck__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Truck__c/Truck__c.object-meta.xml
<CustomObject>
    <label>Truck</label>
    <nameField>
        <label>Plate #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck__c/fields/Current_Location__c.field-meta.xml
<CustomField>
    <fullName>Current_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Location</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Trucks (Current Location)</relationshipLabel>
    <relationshipName>Trucks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Truck__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parked</fullName>
                <default>true</default>
                <label>Parked</label>
            </value>
            <value>
                <fullName>On Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeliveryTriggerHandler.cls
public class DeliveryTriggerHandler {
    
    public static void truckStatusInsertUpdate(List<Delivery__c> deliList){
        //container for bulkify update
        List<Truck__c> updateTruck = new List<Truck__c>();
		
        List<String> truckIdList = new List<String>();
        for(Delivery__c truck : deliList){
            //add truck ids to containers
            truckIdList.add(truck.Truck__c);
        }
        
        List<Truck__c> truckList = [SELECT Id, Status__c
                                    FROM Truck__c
                                    WHERE Id IN :truckIdList];
        
        for(Delivery__c del : deliList){
            for(Truck__c truck : truckList){
                if(del.Status__c == 'Parked' || del.Status__c == 'En-route'){
                    truck.Status__c = 'On Delivery';
                    updateTruck.add(truck);
                }
                else if(del.Status__c == 'Completed'){
                    truck.Status__c = 'Parked';
                    truck.Current_Location__c = del.To_Warehouse__c;
                    updateTruck.add(truck);
                }
            }
                
        }
        //bulkify update
        update truckList; 
    }

}